[project]
name = "2025-07-03-transcendence-poisson-distribution"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pyqt5>=5.15.11",
    "scipy>=1.16.0",
]
